-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-11-10 12:28:32 SGT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE barang (
    id_barang                CHAR(10) NOT NULL,
    nama                     VARCHAR2(20) NOT NULL,
    jumlah                   INTEGER NOT NULL,
    peminjaman_id_peminjaman CHAR(10) NOT NULL
);

ALTER TABLE barang ADD CONSTRAINT barang_pk PRIMARY KEY ( id_barang );

CREATE TABLE mahasiswa (
    id_mahasiswa CHAR(10) NOT NULL,
    nim          INTEGER NOT NULL,
    nama         VARCHAR2(20) NOT NULL,
    password     VARCHAR2(20) NOT NULL
);

ALTER TABLE mahasiswa ADD CONSTRAINT mahasiswa_pk PRIMARY KEY ( id_mahasiswa );

CREATE TABLE peminjaman (
    id_peminjaman          CHAR(10) NOT NULL,
    tanggal_peminjaman     DATE NOT NULL,
    tanggal_kembali        DATE NOT NULL,
    status                 VARCHAR2(12) NOT NULL,
    ruangan_id_ruangan     CHAR(10) NOT NULL,
    mahasiswa_id_mahasiswa CHAR(10) NOT NULL,
    staff_id_staff         CHAR(10) NOT NULL
);

CREATE UNIQUE INDEX peminjaman__idxv1 ON
    peminjaman (ruangan_id_ruangan);

ALTER TABLE peminjaman ADD CONSTRAINT peminjaman_pk PRIMARY KEY ( id_peminjaman );

CREATE TABLE riwayat_peminjaman (
    id_riwayat_peminjaman    CHAR(10) NOT NULL,
    tanggal_pengajuan        DATE NOT NULL,
    tanggal_persetujuan      DATE NOT NULL,
    status                   VARCHAR2(10) NOT NULL,
    peminjaman_id_peminjaman CHAR(10) NOT NULL
);

CREATE UNIQUE INDEX riwayat_peminjaman__idx ON
    riwayat_peminjaman (peminjaman_id_peminjaman);

ALTER TABLE riwayat_peminjaman ADD CONSTRAINT riwayat_peminjaman_pk PRIMARY KEY ( id_riwayat_peminjaman );

CREATE TABLE ruangan (
    id_ruangan CHAR(20) NOT NULL,
    nama       VARCHAR2(20) NOT NULL,
    gedung     VARCHAR2(10) NOT NULL,
    fasilitas  VARCHAR2(20) NOT NULL
);

ALTER TABLE ruangan ADD CONSTRAINT ruangan_pk PRIMARY KEY ( id_ruangan );

CREATE TABLE staff (
    id_staff CHAR(10) NOT NULL,
    nama     VARCHAR2(20) NOT NULL,
    jabatan  VARCHAR2(12) NOT NULL,
    no_telp  INTEGER NOT NULL
);

ALTER TABLE staff ADD CONSTRAINT staff_pk PRIMARY KEY ( id_staff );

ALTER TABLE barang
    ADD CONSTRAINT barang_peminjaman_fk FOREIGN KEY ( peminjaman_id_peminjaman )
        REFERENCES peminjaman ( id_peminjaman );

ALTER TABLE peminjaman
    ADD CONSTRAINT peminjaman_mahasiswa_fk FOREIGN KEY ( mahasiswa_id_mahasiswa )
        REFERENCES mahasiswa ( id_mahasiswa );

ALTER TABLE peminjaman
    ADD CONSTRAINT peminjaman_ruangan_fk FOREIGN KEY ( ruangan_id_ruangan )
        REFERENCES ruangan ( id_ruangan );

ALTER TABLE peminjaman
    ADD CONSTRAINT peminjaman_staff_fk FOREIGN KEY ( staff_id_staff )
        REFERENCES staff ( id_staff );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             2
-- ALTER TABLE                             10
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   2
-- WARNINGS                                 0
