/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Database.DatabaseConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author HP
 */
    // Ubah konstruktor atau method initComponents
    public class CrudBarang extends javax.swing.JFrame {
    int xx, xy;
    DefaultTableModel model;

    /**
     * Creates new form CRUD
     */
    public CrudBarang() {
        initComponents();
        String[] kolom = {"Kode Barang", "Nama Barang", "Stok"};
        model = new DefaultTableModel(kolom, 0) {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 2) { // Kolom "Stok"
                    return Integer.class; // Pastikan kolom "Stok" dikenali sebagai Integer
                }
                return String.class; // Kolom lainnya tetap sebagai String
            }
        };
        tabel_crud_barang.setModel(model);
        tabel_crud_barang.setAutoCreateRowSorter(true); // Aktifkan sorting otomatis
        loadData();
    }

    private void loadData() {
        model.setRowCount(0); // Bersihkan tabel
        String query = "SELECT id_barang, nama, jumlah FROM barang";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(query);
             ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                String idBarang = rs.getString("id_barang");
                String nama = rs.getString("nama");
                int jumlah = rs.getInt("jumlah");
                model.addRow(new Object[]{idBarang, nama, jumlah});
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }

    private void filterTable(String keyword) {
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tabel_crud_barang.setRowSorter(sorter);

        if (keyword.isEmpty()) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + keyword));
        }
    }

    private void clearFields() {
        t_kodebarang.setText("");
        t_nama.setText("");
        t_stock.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_crud_barang = new javax.swing.JTable();
        t_kodebarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t_stock = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t_nama = new javax.swing.JTextField();
        t_pencarian = new javax.swing.JTextField();
        b_tambah = new javax.swing.JButton();
        b_update = new javax.swing.JButton();
        b_batal = new javax.swing.JButton();
        b_hapus = new javax.swing.JButton();
        label_dispose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        tabel_crud_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Stok"
            }
        ));
        tabel_crud_barang.setRowHeight(30);
        tabel_crud_barang.setShowGrid(true);
        jScrollPane1.setViewportView(tabel_crud_barang);

        t_kodebarang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_kodebarang.setBorder(null);
        t_kodebarang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_kodebarangFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_kodebarangFocusLost(evt);
            }
        });
        t_kodebarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_kodebarangActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 51, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kode Barang");

        jLabel5.setBackground(new java.awt.Color(0, 51, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Stok");

        t_stock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_stock.setBorder(null);
        t_stock.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_stockFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_stockFocusLost(evt);
            }
        });
        t_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_stockActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(0, 51, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nama Barang");

        t_nama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_nama.setBorder(null);
        t_nama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_namaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_namaFocusLost(evt);
            }
        });
        t_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_namaActionPerformed(evt);
            }
        });

        t_pencarian.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        t_pencarian.setForeground(new java.awt.Color(0, 102, 255));
        t_pencarian.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_pencarian.setText("Search......");
        t_pencarian.setBorder(null);
        t_pencarian.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_pencarianFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_pencarianFocusLost(evt);
            }
        });
        t_pencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_pencarianActionPerformed(evt);
            }
        });

        b_tambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_tambah.setForeground(new java.awt.Color(0, 102, 255));
        b_tambah.setText("Tambah");
        b_tambah.setAlignmentY(0.0F);
        b_tambah.setBorder(null);
        b_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tambahActionPerformed(evt);
            }
        });

        b_update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_update.setForeground(new java.awt.Color(0, 102, 255));
        b_update.setText("Update");
        b_update.setAlignmentY(0.0F);
        b_update.setBorder(null);
        b_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_updateActionPerformed(evt);
            }
        });

        b_batal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_batal.setForeground(new java.awt.Color(0, 102, 255));
        b_batal.setText("Batal");
        b_batal.setAlignmentY(0.0F);
        b_batal.setBorder(null);
        b_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_batalActionPerformed(evt);
            }
        });

        b_hapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_hapus.setForeground(new java.awt.Color(0, 102, 255));
        b_hapus.setText("Hapus");
        b_hapus.setAlignmentY(0.0F);
        b_hapus.setBorder(null);
        b_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_hapusActionPerformed(evt);
            }
        });

        label_dispose.setBackground(new java.awt.Color(0, 51, 255));
        label_dispose.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_dispose.setForeground(new java.awt.Color(255, 255, 255));
        label_dispose.setText("EXIT");
        label_dispose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_disposeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(t_kodebarang, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(t_nama, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addComponent(t_stock))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(b_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b_update, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(b_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(t_pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_dispose)))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t_pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_dispose))
                        .addGap(16, 16, 16)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(t_kodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void t_kodebarangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_kodebarangFocusGained
        String username = t_kodebarang.getText();
        if(username.equals("Username")) {
            t_kodebarang.setText("");
        }
    }//GEN-LAST:event_t_kodebarangFocusGained

    private void t_kodebarangFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_kodebarangFocusLost
        String username = t_kodebarang.getText();
        if(username.equals("")||username.equals("Username")) {
            t_kodebarang.setText("Username");
        }
    }//GEN-LAST:event_t_kodebarangFocusLost

    private void t_kodebarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_kodebarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_kodebarangActionPerformed

    private void t_stockFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_stockFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_t_stockFocusGained

    private void t_stockFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_stockFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_t_stockFocusLost

    private void t_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_stockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_stockActionPerformed

    private void t_namaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_namaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namaFocusGained

    private void t_namaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_namaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namaFocusLost

    private void t_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namaActionPerformed

    private void t_pencarianFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_pencarianFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_t_pencarianFocusGained

    private void t_pencarianFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_pencarianFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_t_pencarianFocusLost

    private void t_pencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_pencarianActionPerformed
        // TODO add your handling code here:
        String searchQuery = t_pencarian.getText().trim().toLowerCase(); // Ambil input dari t_pencarian
        filterTable(searchQuery); // Lakukan pencarian menggunakan filterTable
    }//GEN-LAST:event_t_pencarianActionPerformed

    private void b_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tambahActionPerformed
        // TODO add your handling code here:
        String idBarang = t_kodebarang.getText().trim();
        String nama = t_nama.getText().trim();
        String stokText = t_stock.getText().trim();

        if (idBarang.isEmpty() || nama.isEmpty() || stokText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int stok;
        try {
            stok = Integer.parseInt(stokText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Stok harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String query = "INSERT INTO barang (id_barang, nama, jumlah) VALUES (?, ?, ?)";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(query)) {

            stmt.setString(1, idBarang);
            stmt.setString(2, nama);
            stmt.setInt(3, stok);
            stmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
            loadData(); // Refresh tabel
            clearFields(); // Bersihkan input
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menambah data: " + e.getMessage());
        }
    }//GEN-LAST:event_b_tambahActionPerformed

    private void b_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_updateActionPerformed
        // TODO add your handling code here:
        String idBarang = t_kodebarang.getText().trim();
        String nama = t_nama.getText().trim();
        String stokText = t_stock.getText().trim();

        if (idBarang.isEmpty() || nama.isEmpty() || stokText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int stok;
        try {
            stok = Integer.parseInt(stokText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Stok harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String query = "UPDATE barang SET nama = ?, jumlah = ? WHERE id_barang = ?";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(query)) {

            stmt.setString(1, nama);
            stmt.setInt(2, stok);
            stmt.setString(3, idBarang);
            stmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
            loadData(); // Refresh tabel
            clearFields(); // Bersihkan input
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui data: " + e.getMessage());
        }
    }//GEN-LAST:event_b_updateActionPerformed

    private void b_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_batalActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_b_batalActionPerformed

    private void b_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_hapusActionPerformed
        // TODO add your handling code here:
        String idBarang = t_kodebarang.getText().trim();

        if (idBarang.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kode Barang harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String query = "DELETE FROM barang WHERE id_barang = ?";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(query)) {

            stmt.setString(1, idBarang);
            stmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            loadData(); // Refresh tabel
            clearFields(); // Bersihkan input
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage());
        }
    }//GEN-LAST:event_b_hapusActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void label_disposeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_disposeMouseClicked
        dispose();
    }//GEN-LAST:event_label_disposeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_batal;
    private javax.swing.JButton b_hapus;
    private javax.swing.JButton b_tambah;
    private javax.swing.JButton b_update;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_dispose;
    private javax.swing.JTextField t_kodebarang;
    private javax.swing.JTextField t_nama;
    private javax.swing.JTextField t_pencarian;
    private javax.swing.JTextField t_stock;
    private javax.swing.JTable tabel_crud_barang;
    // End of variables declaration//GEN-END:variables
}
