/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Database.DatabaseConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author HP
 */
public class CrudRuang extends javax.swing.JFrame {
    int xx, xy;
    DefaultTableModel model;

    public CrudRuang() {
        initComponents();
        String[] kolom = {"Kode Ruangan", "Tipe Ruangan", "Ketersediaan"};
        model = new DefaultTableModel(kolom, 0);
        tabel_crud_ruang.setModel(model);
        tabel_crud_ruang.setAutoCreateRowSorter(true); // Enable sorting
        loadData();
    }

    private void clearFields() {
        t_koderuang.setText("");
        t_tipe.setText("");
        combox_ruang.setSelectedIndex(0); // Set default ke "Tersedia"
    }

    private void loadData() {
        model.setRowCount(0); // Membersihkan tabel

        // Query untuk menggabungkan tabel peminjaman dan ruangan
        String query = "SELECT ruangan.id_ruangan, ruangan.nama, peminjaman.status " +
                       "FROM ruangan " +
                       "LEFT JOIN peminjaman ON ruangan.id_ruangan = peminjaman.id_ruangan";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(query);
             ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                String idRuangan = rs.getString("id_ruangan");
                String namaRuangan = rs.getString("nama");
                String status = rs.getString("status");

                // Tambahkan data ke tabel
                Object[] row = {idRuangan, namaRuangan, status};
                model.addRow(row);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }



    private void filterTable(String keyword) {
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tabel_crud_ruang.setRowSorter(sorter);

        if (keyword.isEmpty()) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + keyword));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_crud_ruang = new javax.swing.JTable();
        t_koderuang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t_tipe = new javax.swing.JTextField();
        t_search = new javax.swing.JTextField();
        b_tambah = new javax.swing.JButton();
        b_update = new javax.swing.JButton();
        b_batal = new javax.swing.JButton();
        b_hapus = new javax.swing.JButton();
        label_dispose = new javax.swing.JLabel();
        combox_ruang = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        tabel_crud_ruang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode Ruangan", "Tipe Ruangan", "Ketersediaan"
            }
        ));
        tabel_crud_ruang.setRowHeight(30);
        tabel_crud_ruang.setShowGrid(true);
        jScrollPane1.setViewportView(tabel_crud_ruang);

        t_koderuang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_koderuang.setBorder(null);
        t_koderuang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_koderuangFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_koderuangFocusLost(evt);
            }
        });
        t_koderuang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_koderuangActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 51, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kode Ruangan");

        jLabel5.setBackground(new java.awt.Color(0, 51, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ketersediaan");

        jLabel6.setBackground(new java.awt.Color(0, 51, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tipe Ruangan");

        t_tipe.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_tipe.setBorder(null);
        t_tipe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_tipeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_tipeFocusLost(evt);
            }
        });
        t_tipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_tipeActionPerformed(evt);
            }
        });

        t_search.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        t_search.setForeground(new java.awt.Color(0, 102, 255));
        t_search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_search.setText("Search......");
        t_search.setBorder(null);
        t_search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_searchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_searchFocusLost(evt);
            }
        });
        t_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_searchActionPerformed(evt);
            }
        });

        b_tambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_tambah.setForeground(new java.awt.Color(0, 102, 255));
        b_tambah.setText("Tambah");
        b_tambah.setAlignmentY(0.0F);
        b_tambah.setBorder(null);
        b_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tambahActionPerformed(evt);
            }
        });

        b_update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_update.setForeground(new java.awt.Color(0, 102, 255));
        b_update.setText("Update");
        b_update.setAlignmentY(0.0F);
        b_update.setBorder(null);
        b_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_updateActionPerformed(evt);
            }
        });

        b_batal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_batal.setForeground(new java.awt.Color(0, 102, 255));
        b_batal.setText("Batal");
        b_batal.setAlignmentY(0.0F);
        b_batal.setBorder(null);
        b_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_batalActionPerformed(evt);
            }
        });

        b_hapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_hapus.setForeground(new java.awt.Color(0, 102, 255));
        b_hapus.setText("Hapus");
        b_hapus.setAlignmentY(0.0F);
        b_hapus.setBorder(null);
        b_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_hapusActionPerformed(evt);
            }
        });

        label_dispose.setBackground(new java.awt.Color(0, 51, 255));
        label_dispose.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_dispose.setForeground(new java.awt.Color(255, 255, 255));
        label_dispose.setText("EXIT");
        label_dispose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_disposeMouseClicked(evt);
            }
        });

        combox_ruang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tersedia", "Tidak Tersedia" }));
        combox_ruang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combox_ruangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t_koderuang, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(t_tipe, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(b_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(b_update, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(b_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(b_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(combox_ruang, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(t_search, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_dispose)))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t_search, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_dispose))
                        .addGap(16, 16, 16)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(t_koderuang, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_tipe, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combox_ruang, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void t_koderuangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_koderuangFocusGained
        String username = t_koderuang.getText();
        if(username.equals("Username")) {
            t_koderuang.setText("");
        }
    }//GEN-LAST:event_t_koderuangFocusGained

    private void t_koderuangFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_koderuangFocusLost
        String username = t_koderuang.getText();
        if(username.equals("")||username.equals("Username")) {
            t_koderuang.setText("Username");
        }
    }//GEN-LAST:event_t_koderuangFocusLost

    private void t_koderuangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_koderuangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_koderuangActionPerformed

    private void t_tipeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_tipeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_t_tipeFocusGained

    private void t_tipeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_tipeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_t_tipeFocusLost

    private void t_tipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_tipeActionPerformed
        // TODO add your handling code here:
        String keyword = t_search.getText().trim();
        filterTable(keyword); // Panggil fungsi filter
    }//GEN-LAST:event_t_tipeActionPerformed

    private void t_searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_searchFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_t_searchFocusGained

    private void t_searchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_searchFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_t_searchFocusLost

    private void t_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_searchActionPerformed
        // TODO add your handling code here:
        String keyword = t_search.getText().trim();
        filterTable(keyword); // Panggil fungsi filter
    }//GEN-LAST:event_t_searchActionPerformed

    private void b_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tambahActionPerformed
        // TODO add your handling code here:
        String kodeRuangan = t_koderuang.getText().trim();
        String tipeRuangan = t_tipe.getText().trim();
        String ketersediaan = combox_ruang.getSelectedItem().toString();

        if (kodeRuangan.isEmpty() || tipeRuangan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String query = "INSERT INTO peminjaman (id_ruangan, nama, status) VALUES (?, ?, ?)";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(query)) {

            stmt.setString(1, kodeRuangan);
            stmt.setString(2, tipeRuangan);
            stmt.setString(3, ketersediaan);
            stmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
            loadData(); // Refresh tabel
            clearFields(); // Bersihkan input
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menambah data: " + e.getMessage());
        }
    }//GEN-LAST:event_b_tambahActionPerformed

    private void b_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_updateActionPerformed
        // TODO add your handling code here:
        String kodeRuangan = t_koderuang.getText().trim();
        String tipeRuangan = t_tipe.getText().trim();
        String ketersediaan = combox_ruang.getSelectedItem().toString();

        if (kodeRuangan.isEmpty() || tipeRuangan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String query = "UPDATE peminjaman SET nama = ?, status = ? WHERE id_ruangan = ?";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(query)) {

            stmt.setString(1, tipeRuangan);
            stmt.setString(2, ketersediaan);
            stmt.setString(3, kodeRuangan);
            stmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
            loadData(); // Refresh tabel
            clearFields(); // Bersihkan input
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui data: " + e.getMessage());
        }
    }//GEN-LAST:event_b_updateActionPerformed

    private void b_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_batalActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_b_batalActionPerformed

    private void b_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_hapusActionPerformed
        // TODO add your handling code here:
        String kodeRuangan = t_koderuang.getText().trim();

        if (kodeRuangan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kode Ruangan harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String query = "DELETE FROM peminjaman WHERE id_ruangan = ?";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(query)) {

            stmt.setString(1, kodeRuangan);
            stmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            loadData(); // Refresh tabel
            clearFields(); // Bersihkan input
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage());
        }
    }//GEN-LAST:event_b_hapusActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void label_disposeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_disposeMouseClicked
        dispose();
    }//GEN-LAST:event_label_disposeMouseClicked

    private void combox_ruangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combox_ruangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combox_ruangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudRuang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_batal;
    private javax.swing.JButton b_hapus;
    private javax.swing.JButton b_tambah;
    private javax.swing.JButton b_update;
    private javax.swing.JComboBox<String> combox_ruang;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_dispose;
    private javax.swing.JTextField t_koderuang;
    private javax.swing.JTextField t_search;
    private javax.swing.JTextField t_tipe;
    private javax.swing.JTable tabel_crud_ruang;
    // End of variables declaration//GEN-END:variables
}
